import { Download } from "lucide-react"
import type { Metadata } from "next"
import { getTranslations } from "next-intl/server"

import { Star } from "@/components/brand/star"
import { CopyLink } from "@/components/qr/copy-link"
import { buttonVariants } from "@/components/ui/button"
import { qrSvg } from "@/lib/qr"
import { publicAppUrl } from "@/lib/site"
import { cn } from "@/lib/utils"

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations("qr")
  return { title: t("metaTitle"), description: t("intro") }
}

// Shareable / printable QR code that opens the landing page. Static and free:
// generated by the app itself, no third-party QR service involved.
export default async function QrPage() {
  const t = await getTranslations("qr")
  const url = publicAppUrl()
  const svg = qrSvg({ size: 480 })

  return (
    <div className="mx-auto flex max-w-5xl flex-wrap items-center justify-center gap-14">
      <div className="rise-in relative">
        <Star spin className="pointer-events-none absolute -left-10 -top-10 size-24 text-primary" />
        <div
          role="img"
          aria-label={t("qrAlt", { url })}
          className="relative w-[min(78vw,420px)] overflow-hidden rounded-[36px] bg-[#f1ebf8] p-5 [&>svg]:h-auto [&>svg]:w-full"
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      </div>

      <div className="flex min-w-0 max-w-md flex-[1_1_320px] flex-col gap-6">
        <p className="eyebrow flex items-center gap-2.5">
          <span className="pulse-dot inline-block size-2 rounded-full bg-spark" aria-hidden />
          {t("eyebrow")}
        </p>
        <h1 className="text-[clamp(2.75rem,7vw,4.5rem)] font-extrabold leading-[0.95]">
          {t("title")} <span className="serif-accent text-primary">{t("accent")}</span>
        </h1>
        <p className="text-lg leading-relaxed text-muted-foreground">{t("intro")}</p>
        <p className="rounded-full border bg-card px-5 py-3 font-medium">{url.replace(/^https?:\/\//, "")}</p>

        <div className="flex flex-wrap gap-2.5">
          <a href="/qr/png" download="starbonds-qr.png" className={cn(buttonVariants({ size: "lg" }), "press")}>
            <Download aria-hidden />
            {t("downloadPng")}
          </a>
          <a href="/qr/svg" download="starbonds-qr.svg" className={cn(buttonVariants({ variant: "outline", size: "lg" }), "press")}>
            <Download aria-hidden />
            {t("downloadSvg")}
          </a>
          <CopyLink url={url} label={t("copy")} copiedLabel={t("copied")} />
        </div>
        <p className="text-sm text-muted-foreground">{t("tips")}</p>
      </div>
    </div>
  )
}
