-- STARBONDS: reference tags (bilingual) used by onboarding, matching and marketplace filters

insert into public.tags (slug, kind, name_es, name_en) values
  -- mediums
  ('painting', 'medium', 'Pintura', 'Painting'),
  ('drawing', 'medium', 'Dibujo', 'Drawing'),
  ('illustration', 'medium', 'Ilustración', 'Illustration'),
  ('digital-art', 'medium', 'Arte digital', 'Digital art'),
  ('photography', 'medium', 'Fotografía', 'Photography'),
  ('sculpture', 'medium', 'Escultura', 'Sculpture'),
  ('ceramics', 'medium', 'Cerámica', 'Ceramics'),
  ('printmaking', 'medium', 'Grabado', 'Printmaking'),
  ('textile', 'medium', 'Textil', 'Textile'),
  ('street-art', 'medium', 'Arte urbano', 'Street art'),
  ('animation', 'medium', 'Animación', 'Animation'),
  ('3d', 'medium', '3D', '3D'),
  ('comics', 'medium', 'Cómic', 'Comics'),
  ('tattoo', 'medium', 'Tatuaje', 'Tattoo'),
  ('collage', 'medium', 'Collage', 'Collage'),
  ('mixed-media', 'medium', 'Técnica mixta', 'Mixed media'),
  ('jewelry', 'medium', 'Joyería', 'Jewelry'),
  ('music', 'medium', 'Música', 'Music'),
  -- styles
  ('abstract', 'style', 'Abstracto', 'Abstract'),
  ('realism', 'style', 'Realismo', 'Realism'),
  ('surrealism', 'style', 'Surrealismo', 'Surrealism'),
  ('minimalism', 'style', 'Minimalismo', 'Minimalism'),
  ('pop-art', 'style', 'Pop art', 'Pop art'),
  ('anime-manga', 'style', 'Anime / Manga', 'Anime / Manga'),
  ('impressionism', 'style', 'Impresionismo', 'Impressionism'),
  ('expressionism', 'style', 'Expresionismo', 'Expressionism'),
  ('contemporary', 'style', 'Contemporáneo', 'Contemporary'),
  ('fantasy', 'style', 'Fantasía', 'Fantasy'),
  ('graffiti', 'style', 'Graffiti', 'Graffiti'),
  ('folk-art', 'style', 'Arte popular', 'Folk art'),
  ('conceptual', 'style', 'Conceptual', 'Conceptual'),
  ('portrait', 'style', 'Retrato', 'Portrait'),
  ('landscape', 'style', 'Paisaje', 'Landscape'),
  -- goals
  ('collaborate', 'goal', 'Colaborar en proyectos', 'Collaborate on projects'),
  ('sell', 'goal', 'Vender mi obra', 'Sell my work'),
  ('commissions', 'goal', 'Aceptar comisiones', 'Take commissions'),
  ('exhibit', 'goal', 'Exponer', 'Exhibit'),
  ('learn', 'goal', 'Aprender', 'Learn'),
  ('teach', 'goal', 'Enseñar', 'Teach'),
  ('find-mentor', 'goal', 'Buscar mentor', 'Find a mentor'),
  ('mentor', 'goal', 'Ser mentor', 'Mentor others'),
  ('feedback', 'goal', 'Recibir feedback', 'Get feedback'),
  ('community', 'goal', 'Hacer comunidad', 'Build community')
on conflict (slug) do nothing;
